 # Find all the available rules by running:
 # swiftlint rules

disabled_rules:
- identifier_name
- cyclomatic_complexity
- type_body_length
- file_length
- function_body_length

line_length: 500

# some rules are only opt-in
force_cast: warning
force_try: warning
trailing_whitespace: warning
shorthand_operator: warning

opt_in_rules:
 - closure_spacing
 - explicit_init
 - extension_access_modifier
 - fatal_error_message
 - first_where
 - implicitly_unwrapped_optional
 - multiline_parameters
 - nimble_operator
 - object_literal
 - operator_usage_whitespace
 - overridden_super_call
 - private_outlet
 - prohibited_super_call
 - redundant_nil_coalescing
 - switch_case_on_newline
 - missing_docs
 - force_unwrapping

# exclude projects & frameworks integrated through carthage/cocoapods
excluded:
 - Carthage
 - Pods
 - vendor
 - External